version: "3.3"

services:

  db:
    image: postgres:13.2
    container_name: wheater_station_db
    restart: always
    volumes:
      - ../database:/var/lib/postgresql/data

    env_file:
      - ../wheater_station/wheater_station/.env
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    image: adminer:4.8.0
    restart: always
    ports:
      - 8080:8080
    depends_on: ["db"]

  app:
    # "build" is the place from where it takes the files to generate the image.
    # build: .
    build: ../wheater_station
    # Imágen to use:
    image: wheater_station
    # Container name:
    container_name: wheater_station
    # Behavior before failures and when starting the system:
    restart: always
    # Linked folders:
    volumes:
      # Source code directory:
      - type: bind
        source: ../wheater_station/wheater_station/core/tools/docker_startup/
        target: /app
    # Used ports:
    ports:
      - 8082:8082

    # Cosole control:
    stdin_open: true
    tty: true
    env_file:
      - ../wheater_station/wheater_station/.env
    # Command to execute at start:
    # command: sh -c "while true; do sleep 1; done"
    command: python startup.py
    depends_on: ["db"]